### ISSUE TITLE
AccountState constructor failure

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1005]
Code below will throw unexpected Exception:
```csharp
byte[] value = new AccountState()
{
    Votes = new ECPoint[] { ECCurve.Secp256r1.G }
}.ToByteArray();
AccountState state = new AccountState(value);
```

System.FormatException
  StackTrace:
   at Neo.IO.Helper.ReadVarInt(BinaryReader reader, UInt64 max)
   at Neo.IO.Helper.ReadVarBytes(BinaryReader reader, Int32 max)
   at Neo.SmartContract.Helper.DeserializeStackItem(BinaryReader reader, UInt32 maxArraySize, UInt32 maxItemSize)
   at Neo.SmartContract.Helper.DeserializeStackItem(Byte[] data, UInt32 maxArraySize, UInt32 maxItemSize)
   at Neo.SmartContract.Native.Tokens.Nep5AccountState.FromByteArray(Byte[] data)
   at Neo.SmartContract.Native.Tokens.Nep5AccountState..ctor(Byte[] data)
   at Neo.SmartContract.Native.Tokens.NeoToken.AccountState..ctor(Byte[] data)
   at Neo.UnitTests.SmartContract.Native.Tokens.UT_NeoToken.TestVote()

Test case can be found here:
https://github.com/eryeer/neoUT/blob/1e503440a818c64078f82c3fabcf914994698abe/neo.UnitTests/SmartContract/Native/Tokens/UT_NeoToken.cs#L464-L468

**Comment by shargon** [comment]
Please review this fix https://github.com/neo-project/neo/pull/1006
