### ISSUE TITLE
Error with ReferenceCounter

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1330]
**Describe the bug**

While updating the dev-pack I found that some SmartContracts doesn't work as expected. 

![image](https://user-images.githubusercontent.com/3167973/70234209-7080a600-1760-11ea-80f7-cc02fc1cd2d5.png)

The failure resides here https://github.com/neo-project/neo-vm/blob/f29d46460df8507899ff955363c6f3b90a807337/src/neo-vm/ReferenceCounter.cs#L68, at the beginning I thought that was because some Arrays was without Reference Counter so I made #1329 but as you can see in the image, all of them have the reference Counter

**Comment by erikzhang** [comment]
What is the exception?

**Comment by erikzhang** [comment]
Okay. I know the reason. I will fix it.

**Comment by shargon** [comment]
```System.Collections.Generic.KeyNotFoundException: The given key 'Neo.VM.Types.Array' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.VM.ReferenceCounter.CheckZeroReferred() in C:\Sources\Neo\neo-vm\src\neo-vm\ReferenceCounter.cs:line 70
System.NullReferenceException: Object reference not set to an instance of an object.
   at Neo.VM.ReferenceCounter.CheckZeroReferred() in C:\Sources\Neo\neo-vm\src\neo-vm\ReferenceCounter.cs:line 74
   at Neo.VM.ExecutionEngine.PostExecuteInstruction(Instruction instruction) in C:\Sources\Neo\neo-vm\src\neo-vm\ExecutionEngine.cs:line 1034
   at Neo.VM.ExecutionEngine.ExecuteNext() in C:\Sources\Neo\neo-vm\src\neo-vm\ExecutionEngine.cs:line 116```
