### ISSUE TITLE
Akka error when neo-cli exit

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo#1615]
**Describe the bug**
A exception about akka when neo-cli `exit`.

**To Reproduce**
1. Run neo-cli
2. Waitting connect nodes and start synchronizing block
3. Run `exit` command.

**Expected behavior**
No exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/12728872/80328198-37f97a00-8871-11ea-8f49-40893d0e38cd.png)

**Platform:**
 - OS: Windows 10 x64
 - Version: neo3 preview2

**(Optional) Additional context**
Exception content:
```
[ERROR][2020/4/27 2:23:38][Thread 0027][akka://NeoSystem/system/IO-TCP/$i] Monitored actor [[akka://NeoSystem/user/$b#1433939172]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#1433939172]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.ReceivedTerminated(Terminated t)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

**Comment by erikzhang** [comment]
@ProDog Has it been fixed?

**Comment by shargon** [comment]
No response from @ProDog
