### ISSUE TITLE
Fixed8 fails to work with big decimals

### ISSUE THREAD

**Issue by osmirnov** [neo-project/neo#207]
Test:
```C#
        [TestMethod]
        public void Can_multiply_without_overflow()
        {
            decimal a = (Decimal.MaxValue - 1m) / 2m;
            decimal b = 2m;
            decimal expected = a * b;
            Fixed8 af = Fixed8.FromDecimal(a); // The overflow exception is here
            Fixed8 bf = Fixed8.FromDecimal(b);
            Fixed8 actual = af * bf;
            ((decimal)actual).Should().Be(expected);
        }
```

Result:
```C#
Test method Neo.UnitTests.UT_Fixed8.Can_multiply_without_overflow threw exception: 
System.OverflowException: Value was either too large or too small for a Decimal.
    at System.Decimal.FCallMultiply(Decimal& d1, Decimal& d2)
   at System.Decimal.op_Multiply(Decimal d1, Decimal d2)
   at Neo.Fixed8.FromDecimal(Decimal value) in C:\Projects\Private\neo\neo\Fixed8.cs:line 82
   at Neo.UnitTests.UT_Fixed8.Can_multiply_without_overflow() in C:\Projects\Private\neo\neo.UnitTests\UT_Fixed8.cs:line 44
```
The reason is a passed value to FromDecimal is bigger than Fixed8.Max.

Is it by design? Could the better input validation be applied?

Thanks.

**Comment by erikzhang** [comment]
Yes, it is by design. The method `FromDecimal` throws `OverflowException` if the value if out of range.
https://github.com/neo-project/neo/blob/70ffddcaa1e7b3beea2d8288d4c6dda05b58df49/neo/Fixed8.cs#L80-L89

**Comment by osmirnov** [comment]
The OverflowException exception I observe happens in line 82, not in 84. Anyway, it is still the same type of the exception.
