### ISSUE TITLE
Pickle fails in python 3.6

### ISSUE THREAD

**Issue by Christian-B** [neo-project/neo#227]
test script:
#code taken from http://neo.readthedocs.io/en/0.6/api_reference.html#neo.core.Block
from neo.core import (Block, Segment, ChannelIndex,  AnalogSignal)
from quantities import nA, kHz
import numpy as np
# create a Block with 3 Segment and 2 ChannelIndex objects
blk = Block()
for ind in range(3):
    seg = Segment(name='segment %d' % ind, index=ind)
    blk.segments.append(seg)

    for ind in range(2):
        chx = ChannelIndex(name='Array probe %d' % ind, index=np.arange(64))
        blk.channel_indexes.append(chx)

# Populate the Block with AnalogSignal objects
    for seg in blk.segments:
        for chx in blk.channel_indexes:
            a = AnalogSignal(np.random.randn(10000, 64)*nA,
                             sampling_rate=10*kHz)
            chx.analogsignals.append(a)
            seg.analogsignals.append(a)

# code to write pickle

from neo.io import PickleIO
import pickle

io = PickleIO(filename="temp.pkl")

io.write(blk)

#code to read pickle back
with open("temp.pkl") as pkl:
    neo = pickle.load(pkl)

===
result
Traceback (most recent call last):
  File ".../test.py", line 34, in <module>
    neo = pickle.load(pkl)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by hal0x2328** [comment]
Wrong project - I think you meant to post this in https://github.com/NeuralEnsemble/python-neo/issues
