### ISSUE TITLE
System.NullReferenceException in Payloads.Block, Payloads.Transaction and Payloads.Signer objects fields

### ISSUE THREAD

**Issue by evgeniygubin** [neo-project/neo#2484]
**Describe the bug**
`Transaction.Hash` and some other fields (`Transaction.FeePerByte`, `Transaction.Size and Signer.Size`) cause `System.NullReferenceException` when trying to use it:

```
at Neo.IO.Helper.Write[T](BinaryWriter writer, IReadOnlyCollection`1 value)
   at Neo.Network.P2P.Payloads.Signer.Serialize(BinaryWriter writer)
   at Neo.IO.Helper.Write[T](BinaryWriter writer, IReadOnlyCollection`1 value)
   at Neo.Network.P2P.Payloads.Transaction.Neo.Network.P2P.Payloads.IVerifiable.SerializeUnsigned(BinaryWriter writer)
   at Neo.Network.P2P.Helper.CalculateHash(IVerifiable verifiable)
   at Neo.Network.P2P.Payloads.Transaction.get_Hash()
   at NeoService.Domain.Model.Wallets.NeoBlockWallet.<FetchTransactionsFromBlock>d__28.MoveNext() in C:\Users\
```
When recieving json result of RPC `GetBlock()` value of `tx/signers/scopes` is `WitnessScope.CustomContracts`, and value of `tx/signers/allowedcontracts` is [], and then after converting it into `Payloads.Signer` object  [`Size`](https://github.com/neo-project/neo/blob/1366e7a54c6681124914e02da3051da0dc188d60/src/neo/Network/P2P/Payloads/Signer.cs#L38) field cause `System.NullReferenceException`. Other field which using `Signer.Size` also cause `System.NullReferenceException`. I guess same exception will be cause with `WitnessScope.CustomGroups` and `AllowedGroups` is `null`.

**To Reproduce**
Call RPC `GetBlock()` method and get `RpcBlock `object for block 33980 on testnet.

**Expected behavior**
Possibility to check these fields for null
Right exception handling in Neo core lib

**Screenshots**
![Screenshot 2021-05-26 193156](https://user-images.githubusercontent.com/50550856/119697851-50afd700-be59-11eb-84cb-b0eaae31d25d.png)
![Screenshot 2021-05-26 193253](https://user-images.githubusercontent.com/50550856/119697993-763ce080-be59-11eb-8061-cd795a0dcea9.png)

**Platform:**
OS: Windows 10 Pro, 20H2 19042.985
Assembly Neo, Version=3.0.0.0, MVID: 9D408606-4DC3-4FA5-B33B-AE24BA5E4A24

**Comment by erikzhang** [comment]
It is caused by https://github.com/neo-project/neo-modules/issues/592
