### ISSUE TITLE
IPersistencePlugin May Lose Data Because of the Disposing Order in NeoSystem.cs

### ISSUE THREAD

**Issue by dusmart** [neo-project/neo#2624]
**Describe the bug**
When we shut down the neo-node by Ctrl-C or `exit` command or any other unexpected method, we will probably lose one block's data for every `IPersistencePlugin` if it's syncing block and using `OnCommit()` for data recording. If `OnPersist()` is used for data recording, no data will be lost while an exception will be thrown.

**Background**
We're trying to build an archive node by adding an `IPersistencePlugin` that records all data at any block height. When we add the `Dispose` method, the DB will always meet a segmentation fault when we stop the neo-node.

**To Reproduce**
1. Open the neo-node, install any `IPersistencePlugin` with `Dispose()` method that releases the essential resouces.
2.  Run `./neo-node`
3. Type `exit` after it starts syncing block

**Expected behavior**
The plugin will cause an exception because of using resources after releasing them.

**Screenshots**
```
   at Neo.Plugins.Storage.Store.Put(Byte[] key, Byte[] value)
   at Neo.Plugins.ArchiveStore.<>c__DisplayClass3_0.<OnPersist>b__0(Trackable v)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Neo.Plugins.ArchiveStore.OnPersist(NeoSystem ns, Block block, DataCache snapshot, IReadOnlyList`1 ae)
   at Neo.Ledger.Blockchain.Persist(Block block)
   at Neo.Ledger.Blockchain.OnImport(IEnumerable`1 blocks, Boolean verify)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
   at Akka.Dispatch.Mailbox.ProcessMailbox(Int32 left, Int64 deadlineTicks)
   at Akka.Dispatch.Mailbox.ProcessMailbox()
   at Akka.Dispatch.Mailbox.<Run>b__36_0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Dispatch.Mailbox.Run()
   at Akka.Dispatch.ThreadPoolExecutorService.<>c.<.cctor>b__3_0(Object t)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[1]    56384 segmentation fault  ./neo-cli
```

https://github.com/neo-project/neo/blob/d092510d0b416f30d5dca7be9913193443bebb96/src/neo/NeoSystem.cs#L164-L174

**Expected code**
Move `EnsureStoped(LocalNode);` before plugins' `Dispose()`.
At least make sure all `IPersistencePlugin`s dispose after the LocalNode is stoped.

Maybe [ApplicationLogs](https://github.com/neo-project/neo-modules/blob/master/src/ApplicationLogs/LogReader.cs#L18) Plugin can add the `Dispose()` method to release DB safely after this issue is solved.

**Comment by Qiao-Jin** [comment]
Similiar issues and PRs which might be usedful for this problem:
https://github.com/neo-project/neo/issues/2570
https://github.com/neo-project/neo-node/issues/816

https://github.com/neo-project/neo/pull/2576
