### ISSUE TITLE
Neo - funds transferred to watch only address

### ISSUE THREAD

**Issue by Michmex** [neo-project/neo#2648]
I have Neo legacy account and I have only claimed the gas and not transferred any amount out.  When I accessed my account on November 6th, I have noticed that all my funds have been transferred. What seems strange is that a small amount of gas was sent to my address and the rest to another unknown address. The new wallet address appears now as "watch only address".  The money has been sitting there ever since with no mouvement. Please note my gas was not emptied from my wallet.  I would greatly appreciate someone's help.

Can someone please help me get access to the Neos in the "watch only address" wallet?

**Comment by ZhangTao1596** [comment]
How did you claim your gas? Which wallet did you use?

**Comment by Michmex** [comment]
Hello,

I claimed the gas directly in the wallet. There is a button which I click on and the amount simply goes to my account and it accumulates there.
I am using the Neon Legacy wallet.  All I did in the last 4 years was claim the gas.  My last transaction you see in the account (AQV..) is I moved the gas out.

***@***.***

When I returned in November I noticed 2 entries with this transaction in my account:
***@***.***
***@***.***
***@***.***

I know this is not a scammer nor a hack, because all my gas remained in my wallet until I moved them out myself.

A hacker would never have left 132 Neos just sitting there in my wallet.

I know other people have mentioned they had this happen to them, but I am not sure the solution they got.

Please let me know if there is something you need to make sense of this.

Thank you.

Michel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Liaojinghui** [comment]
You need to provide more information about the software you use, the version of the software, the address of your account as well as the transaction id if you have it.

**Comment by Michmex** [comment]
Hello,

Here is the information you requested.

Information on the software:

Description on the installer.exe: Light weight for Neo blockchain.
This is a Neo Legacy wallet

Version: V2.9.4
See log below (This error happened shortly after I upgraded to V2.9.4)

[2021-10-22 12:37:57.399] [info] New version 2.9.4 has been downloaded to C:\Users\merli\AppData\Local\neon-updater\pending\Neon.2.9.4.exe
[2021-10-22 12:37:57.407] [info] Update downloaded [object Object]
[2021-10-22 13:40:27.869] [info] Auto install update on quit
[2021-10-22 13:40:27.876] [info] Install: isSilent: true, isForceRunAfter: false
[2021-11-03 13:22:28.056] [info] Checking for update
[2021-11-03 13:22:28.062] [info] Checking for update...
[2021-11-03 13:22:32.003] [info] Update for version 2.9.4 is not available (latest version: 2.9.4, downgrade is disallowed).
[2021-11-03 13:22:32.003] [info] Update not available.
[2021-11-06 15:10:23.725] [info] Checking for update
[2021-11-06 15:10:23.730] [info] Checking for update...
[2021-11-06 15:10:27.263] [info] Update for version 2.9.4 is not available (latest version: 2.9.4, downgrade is disallowed).
[2021-11-06 15:10:27.264] [info] Update not available.
[2021-11-06 16:53:14.987] [info] Checking for update
[2021-11-06 16:53:14.996] [info] Checking for update...
[2021-11-06 16:53:18.963] [info] Update for version 2.9.4 is not available (latest version: 2.9.4, downgrade is disallowed).
[2021-11-06 16:53:18.965] [info] Update not available.
[2021-11-06 16:53:20.321] [info] Checking for update
[2021-11-06 16:53:20.327] [info] Checking for update...
[2021-11-06 16:53:25.394] [info] Update for version 2.9.4 is not available (latest version: 2.9.4, downgrade is disallowed).
[2021-11-06 16:53:25.395] [info] Update not available.
[2021-11-10 10:47:40.390] [info] Checking for update
[2021-11-10 10:47:40.397] [info] Checking for update...
[2021-11-10 10:47:42.424] [error] Error: Error: net::ERR_INTERNET_DISCONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
[2021-11-10 10:47:42.425] [info] Error in auto-updater. Error: net::ERR_INTERNET_DISCONNECTED



My address is: AQvMAfA2v83mUgKiRh5b3h6YrHmKnVyqVC

The unknown address is: AXi29xyuF6UXMWr5eHLMQya7UUQAtqMZeF

The transaction hash: 0xe9639492822f921fad8a47fe507c8d8f92d370ecd621dfab811092ea80a780d5



When I returned in November, the 2 entries of this transaction were in my account:


***@***.***
***@***.***


I know this is not a scammer nor a hack, because all my gas remained in my wallet until I moved them out myself in December.

Please let me know if there is anything else you need.

Thank you.

Michel


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by shargon** [comment]
Neo legacy issue
