### ISSUE TITLE
Storage fails on a specific contract on Testnet t5

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2890]
**Describe the bug**
Contract `0x12fbec62fb765ce3f55845106ccf3717716723ad` on `testnet t5` at block `2588120` is causing the problem. The contract permission is empty (has a bad stackitem in it)?

_**Abi shows no contract permissions `*` but neo seems to think it has two.**_
![image](https://github.com/neo-project/neo/assets/8141309/15f5a8df-7352-4175-856a-c2cbcdb416b8)

```
   at Neo.SmartContract.Manifest.ContractPermissionDescriptor..ctor(ReadOnlySpan`1 span)
   at Neo.SmartContract.Manifest.ContractManifest.<>c.<Neo.SmartContract.IInteroperable.FromStackItem>b__29_3(StackItem p)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Neo.SmartContract.Manifest.ContractManifest.Neo.SmartContract.IInteroperable.FromStackItem(StackItem stackItem)
   at Neo.SmartContract.ContractState.Neo.SmartContract.IInteroperable.FromStackItem(StackItem stackItem)
   at Neo.SmartContract.StorageItem.GetInteroperable[T]()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Neo.Plugins.RpcServer.FindTokenContracts(JArray _params)
   at Neo.Plugins.RpcServer.ProcessRequestAsync(HttpContext context, JObject request)
```
`Value does not fall within the expected range. (Parameter 'span')`

**To Reproduce**
**Any application using this `ListContracts` function will be dead in the water.**
```csharp
var tokenList = NativeContract.ContractManagement.ListContracts(_neosystem.StoreView);
var vaildContracts = tokenList
    .OrderBy(o => o.Manifest.Name)
    .Skip((skip - 1) * take)
    .Take(take);
vaildContracts.Any() // <-- crashes when reading data
```

### Rcp Server
- https://testnet1.neo.coz.io:443
- aka all

### RCP Request
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "getstorage",
    "params": ["0x12fbec62fb765ce3f55845106ccf3717716723ad"]
}
```
### RCP Response
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -2147024809,
        "message": "Value does not fall within the expected range. (Parameter 'span')"
    }
}
```

**Expected behavior**
This was working before for the longest time, and now it doesn't. Something somewhere broken Testnet T5. A stackitem, i think with bad data.

**Comment by roman-khimov** [comment]
Somewhat related to #2829, but a different thing, because NeoGo answers correctly (at least from the first glance).
```
$ curl -sd '{ "jsonrpc": "2.0", "id": 5, "method": "getcontractstate", "params": ["0x12fbec62fb765ce3f55845106ccf3717716723ad"] }' http://seed4t5.neo.org:20332 | json_pp
{
   "id" : 5,
   "error" : {
      "code" : -2147024809,
      "message" : "Value does not fall within the expected range. (Parameter 'span')"
   },
   "jsonrpc" : "2.0"
}
$ curl -sd '{ "jsonrpc": "2.0", "id": 5, "method": "getcontractstate", "params": ["0x12fbec62fb765ce3f55845106ccf3717716723ad"] }' https://rpc.t5.n3.nspcc.ru:20331 | json_pp
{
   "id" : 5,
   "jsonrpc" : "2.0",
   "result" : {
      "id" : 1264,
      "hash" : "0x12fbec62fb765ce3f55845106ccf3717716723ad",
      "nef" : {
         "magic" : 860243278,
         "script" : "VwADDBRYhxcRfgqoEHKvq3HS3Yn+fEuS/nh5DAhjYWxsYmFjawt6FcNKURRQ0EpRE1DQSlESUNBKURFQ0EpREFDQUB9QDAdyZXF1ZXN0UEFifVtSRUBXAARBm/ZnzhB4U0HmPxiEQZv2Z84RelNB5j8YhEGb9mfOEntTQeY/GIRAQfa0a+IQUEGSXegxQEH2tGviEVBBkl3oMUrYJgZFECIE2yFAQfa0a+ISUEGSXegxQA==",
         "source" : "",
         "compiler" : "neow3j-3.20.2",
         "tokens" : [],
         "checksum" : 334253959
      },
      "manifest" : {
         "abi" : {
            "events" : [],
            "methods" : [
               {
                  "name" : "request",
                  "safe" : false,
                  "offset" : 0,
                  "returntype" : "Void",
                  "parameters" : [
                     {
                        "type" : "String",
                        "name" : "url"
                     },
                     {
                        "type" : "String",
                        "name" : "filter"
                     },
                     {
                        "type" : "Integer",
                        "name" : "gasForResponse"
                     }
                  ]
               },
               {
                  "parameters" : [
                     {
                        "name" : "url",
                        "type" : "String"
                     },
                     {
                        "type" : "Any",
                        "name" : "userData"
                     },
                     {
                        "name" : "responseCode",
                        "type" : "Integer"
                     },
                     {
                        "name" : "response",
                        "type" : "ByteArray"
                     }
                  ],
                  "safe" : false,
                  "name" : "callback",
                  "offset" : 86,
                  "returntype" : "Void"
               },
               {
                  "parameters" : [],
                  "name" : "getStoredUrl",
                  "safe" : false,
                  "returntype" : "String",
                  "offset" : 129
               },
               {
                  "returntype" : "Integer",
                  "offset" : 142,
                  "name" : "getStoredResponseCode",
                  "safe" : false,
                  "parameters" : []
               },
               {
                  "safe" : false,
                  "name" : "getStoredResponse",
                  "offset" : 165,
                  "returntype" : "ByteArray",
                  "parameters" : []
               }
            ]
         },
         "supportedstandards" : [],
         "groups" : [],
         "name" : "CallOracleContract-6",
         "trusts" : [
            "0xfe924b7cfe89ddd271abaf7210a80a7e11178758",
            "*"
         ],
         "features" : {},
         "extra" : {},
         "permissions" : [
            {
               "contract" : "0xfe924b7cfe89ddd271abaf7210a80a7e11178758",
               "methods" : "*"
            },
            {
               "contract" : "*",
               "methods" : "*"
            }
         ]
      },
      "updatecounter" : 0
   }
}
```
But we have a stateroot mismatch since 2588120 (https://github.com/nspcc-dev/neo-go/issues/3105), what a coincidence...

**Comment by cschuchardt88** [comment]
>  because NeoGo answers correctly (at least from the first glance).

I think i spotted it?
```json
"permissions" : [
            {
               "contract" : "0xfe924b7cfe89ddd271abaf7210a80a7e11178758",
               "methods" : "*"
            },
            {
               "contract" : "*",
               "methods" : "*"
            }
         ]
```

Also I'm currently unable to work on some projects that use the `ListContracts` method like above.
