### ISSUE TITLE
Invoking Deployed `Contracts` in `ApplicationEngine` on Blockchain vs in `neo-cli` or local

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3088]
**Describe the bug**
When invoking in `neo-cli` i get error `Index was outside the bounds of the array` for a `contract`. Bypassing `ApplicationEngine.Run` in `neo-cli` and just sending the transaction directly to the blockchain _(invoking that way)_; `ApplicationEngine` works fine.

#### TestNet
**Contract**: `0x70b53ba105de41678d0ffe57d62aa4cfd6e4e2db`
**Transaction**: `0x999a71618fcae5f0c21f06d9e648779f8dabc65a0ad4f2c469e973eefdc202d2`

https://dora.coz.io/transaction/neo3/testnet/0x999a71618fcae5f0c21f06d9e648779f8dabc65a0ad4f2c469e973eefdc202d2

```
   at Neo.Network.P2P.Payloads.Transaction.get_Sender() in C:\Users\Chris\Projects\cschuchardt88\neo\src\Neo\Network\P2P\Payloads\Transaction.cs:line 128
   at Neo.Network.P2P.Payloads.Transaction.ToStackItem(ReferenceCounter referenceCounter) in C:\Users\Chris\Projects\cschuchardt88\neo\src\Neo\Network\P2P\Payloads\Transaction.cs:line 461
   at Neo.SmartContract.ApplicationEngine.GetScriptContainer() in C:\Users\Chris\Projects\cschuchardt88\neo\src\Neo\SmartContract\ApplicationEngine.Runtime.cs:line 203
   at InvokeStub_ApplicationEngine.GetScriptContainer(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**To Reproduce**
```csharp
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Attributes;
using Neo.SmartContract.Framework.Native;
using Neo.SmartContract.Framework.Services;
using System.ComponentModel;

namespace HelloWorld;

[DisplayName("GetTransaction")]
[ContractPermission("*", "*")]
public class Contract1 : SmartContract
{
    [Syscall("System.Runtime.GetScriptContainer")]
    public static extern Transaction GetTransaction();

    [DisplayName("_deploy")]
    public static void OnDeployment(object data, bool update)
    {
        if (update)
            return;
    }

    public static void Test() // invoke this method
    {
        if (Runtime.Trigger == TriggerType.Application)
        {
            var tx = GetTransaction();
            var txHash = tx.Hash;
        }
    }

    public static bool Update(ByteString nefFile, string manifest)
    {
        ContractManagement.Update(nefFile, manifest);
        return true;
    }

    public static bool Destroy()
    {
        ContractManagement.Destroy();
        return true;
    }
}
```

**Expected behavior**
Who knows

**Screenshots**
### No Work
![image](https://github.com/neo-project/neo/assets/8141309/9099791e-4b55-4b1f-b5ed-1eb9bcdd16b8)

## Works
![image](https://github.com/neo-project/neo/assets/8141309/a93d0b36-644a-4418-83b2-92afc2391b26)

**Platform:**
 - OS: [e.g. Windows 10 x64]
 - Version neo 3.6.2

**Comment by cschuchardt88** [comment]
@shargon @Jim8y

**Comment by Jim8y** [comment]
Did you make it work on the blockchain？ cause the log can not work on hash.

**Comment by cschuchardt88** [comment]
@Jim8y This without log.
