### ISSUE TITLE
[ProtocolSettings.Default] `NeoSystem` can't Create Genesis Block

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3203]
**Describe the bug**
Default `ProtocolSettings` current doesn't work when creating the `NeoSystem`. This happens because the `StandbyValidators` property is `empty`; this used to work no problem.

Fails `Contract.GetBFTAddress` in the `NeoSysetm.CreateGenesisBlock` `line:162`
---
https://github.com/neo-project/neo/blob/629baf819f9ebedec4b2e89e7b55a5adf1836597/src/Neo/NeoSystem.cs#L152-L162

Failing at `line:106`
---
https://github.com/neo-project/neo/blob/629baf819f9ebedec4b2e89e7b55a5adf1836597/src/Neo/SmartContract/Contract.cs#L103-L106

Keep in mind that `ProtocolSettings.Default` defaults as:
---
https://github.com/neo-project/neo/blob/629baf819f9ebedec4b2e89e7b55a5adf1836597/src/Neo/ProtocolSettings.cs#L108-L121

**To Reproduce**
```csharp
var neoSystem = new NeoSystem(ProtocolSettings.Default, "MemoryStore", null);
```
**Expected behavior**
`ProtocolSettings.Default` to work with NeoSystem. Seeing how `SeedList` is `empty`; you are not connecting to the network.

**Screenshots**
![image](https://github.com/neo-project/neo/assets/8141309/8bf49fdc-6daf-4f92-9f51-929050c66b4b)

**Platform:**
 - OS: Windows 11 x64
 - Version 3.6.2

**(Optional) Additional context**
```log
Exception:
   Value does not fall within the expected range.
Stack Trace:
   at Neo.SmartContract.Contract.CreateMultiSigRedeemScript(Int32 m, IReadOnlyCollection`1 publicKeys) in R:\github\cschuchardt88\neo\src\Neo\SmartContract\Contract.cs:line 106
   at Neo.SmartContract.Contract.GetBFTAddress(IReadOnlyCollection`1 pubkeys) in R:\github\cschuchardt88\neo\src\Neo\SmartContract\Contract.cs:line 152
   at Neo.NeoSystem.CreateGenesisBlock(ProtocolSettings settings) in R:\github\cschuchardt88\neo\src\Neo\NeoSystem.cs:line 152
   at Neo.NeoSystem..ctor(ProtocolSettings settings, IStoreProvider storageProvider, String storagePath) in R:\github\cschuchardt88\neo\src\Neo\NeoSystem.cs:line 134
   at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageProvider, String storagePath) in R:\github\cschuchardt88\neo\src\Neo\NeoSystem.cs:line 120
   at Neo.Hosting.App.Hosting.Services.NeoSystemHostedService.StartAsync(CancellationToken cancellationToken) in R:\github\cschuchardt88\neo\src\Neo.Hosting.App\Hosting\Services\NeoSystemHostedService.cs:line 89
   at Neo.Hosting.App.CommandLine.RunCommand.Handler.InvokeAsync(InvocationContext context) in R:\github\cschuchardt88\neo\src\Neo.Hosting.App\CommandLine\RunCommand.cs:line 49
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Neo.Hosting.App.Extensions.CommandLineBuilderExtensions.<>c__DisplayClass1_0.<<UseInternalHost>b__0>d.MoveNext() in R:\github\cschuchardt88\neo\src\Neo.Hosting.App\Extensions\CommandLineBuilderExtensions.cs:line 58
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

@shargon @Jim8y 
What do we need to do to get this work without adding `PublicKeys` to `StandbyValidators`?

**Comment by roman-khimov** [comment]
> Default ProtocolSettings current doesn't work when creating the NeoSystem

But why do you need it? Tests should use some test-specific configs.
