### ISSUE TITLE
RockDb FileNotFoundException

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#3419]
Sometime ago I was able to run RocksDbStore normally.

Nowadays it is returning a crash
```cs
neo> FATAL [17:14:42.250] 	System.IO.FileNotFoundException
Could not load file or assembly 'RocksDbSharp, Version=8.11.3.46984,  Culture=neutral,  PublicKeyToken=null'. The...ch()
   at  System.Thr...eadStart()
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'RocksDbSharp, Version=8.11.3.46984, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'RocksDbSharp, Version=8.11.3.46984, Culture=neutral, PublicKeyToken=null'
   at Neo.Plugins.Storage.Store..ctor(String path)
   at Neo.Plugins.Storage.RocksDBStore.GetStore(String path)
   at Neo.NeoSystem..ctor(ProtocolSettings settings, IStoreProvider storageProvider, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 136
   at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageProvider, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 120
   at Neo.CLI.MainService.Start(CommandLineOptions options) in /opt/neoLib/src/Neo.CLI/CLI/MainService.cs:line 380
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
/opt/start_node.sh: line 2:   103 Aborted                 (core dumped) dotnet neo-cli.dll
```

The only method I have now in master to run a node in a consensus is MemoryStore. The rest is all bugging.

The configuration I used is the same as before. I run all setup with Docker images.
Build with `mcr.microsoft.com/dotnet/sdk:8.0.303-jammy`
Run with `mcr.microsoft.com/dotnet/aspnet:8.0.7-jammy`

There is no change from previous setup that was successful.

**Comment by cschuchardt88** [comment]
This has to do with running `neo-cli` as a `dll`. You have to call `Plugins.Loaddlls` manually.

**Comment by vncoelho** [comment]
> This has to do with running `neo-cli` as a `dll`. You have to call `Plugins.Loaddlls` manually.

Since when?
This was never a requirement before

**Comment by cschuchardt88** [comment]
> > This has to do with running `neo-cli` as a `dll`. You have to call `Plugins.Loaddlls` manually.
> 
> Since when? This was never a requirement before

I think its a `dotnet` thing with `static` classes. I had to do this for `new-cli`. Because it wasn't loading plugins' store. Could still be wrong.

**Comment by cschuchardt88** [comment]
@vncoelho has problem been resolved?

**Comment by vncoelho** [comment]
@cschuchardt88 I just tried with current master branch and all deps installed

**Comment by Hecate2** [comment]
Does it work now?

**Comment by shargon** [comment]
@vncoelho do you still receiving this error?

**Comment by vncoelho** [comment]
> @vncoelho do you still receiving this error?

I will check asap until tomorrow.

**Comment by vncoelho** [comment]
@shargon, verified and the same error.

```cs
NEO-CLI v3.7.5  -  NEO v3.7.5  -  NEO-VM v3.7.5

neo> FATAL [17:53:28.539] 	System.IO.FileNotFoundException
Could not load file or assembly 'RocksDbSharp, Version=9.4.0.50294,  Culture=neutral,  PublicKeyToken=null'. The...ch()
   at  System.Thr...eadStart()
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'RocksDbSharp, Version=9.4.0.50294, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'RocksDbSharp, Version=9.4.0.50294, Culture=neutral, PublicKeyToken=null'
   at Neo.Plugins.Storage.Store..ctor(String path)
   at Neo.Plugins.Storage.RocksDBStore.GetStore(String path)
   at Neo.NeoSystem..ctor(ProtocolSettings settings, IStoreProvider storageProvider, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 137
   at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageProvider, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 121
   at Neo.CLI.MainService.Start(CommandLineOptions options) in /opt/neoLib/src/Neo.CLI/CLI/MainService.cs:line 381
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
/opt/start_node.sh: line 2:   667 Aborted                 (core dumped) ( cd /opt/node/Neo.CLI/; dotnet neo-cli.dll )
```

Client has 

```dockerfile
RUN apt-get update && apt-get install -y --no-install-recommends \
	    unzip \
	    screen \
	    expect \
	    libsnappy-dev \
	    libleveldb-dev \
	    librocksdb-dev \
```

**Comment by shargon** [comment]
> @shargon, verified and the same error.
> 
> ```cs
> NEO-CLI v3.7.5  -  NEO v3.7.5  -  NEO-VM v3.7.5
> 
> neo> FATAL [17:53:28.539] 	System.IO.FileNotFoundException
> Could not load file or assembly 'RocksDbSharp, Version=9.4.0.50294,  Culture=neutral,  PublicKeyToken=null'. The...ch()
>    at  System.Thr...eadStart()
> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'RocksDbSharp, Version=9.4.0.50294, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> 
> File name: 'RocksDbSharp, Version=9.4.0.50294, Culture=neutral, PublicKeyToken=null'
>    at Neo.Plugins.Storage.Store..ctor(String path)
>    at Neo.Plugins.Storage.RocksDBStore.GetStore(String path)
>    at Neo.NeoSystem..ctor(ProtocolSettings settings, IStoreProvider storageProvider, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 137
>    at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageProvider, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 121
>    at Neo.CLI.MainService.Start(CommandLineOptions options) in /opt/neoLib/src/Neo.CLI/CLI/MainService.cs:line 381
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> /opt/start_node.sh: line 2:   667 Aborted                 (core dumped) ( cd /opt/node/Neo.CLI/; dotnet neo-cli.dll )
> ```
> 
> Client has
> 
> ```dockerfile
> RUN apt-get update && apt-get install -y --no-install-recommends \
> 	    unzip \
> 	    screen \
> 	    expect \
> 	    libsnappy-dev \
> 	    libleveldb-dev \
> 	    librocksdb-dev \
> ```

Could you show us the `ls` output, where is the RocksDbSharp library located?

**Comment by vncoelho** [comment]
> > @shargon, verified and the same error.
> > 
> > ```cs
> > NEO-CLI v3.7.5  -  NEO v3.7.5  -  NEO-VM v3.7.5
> > 
> > neo> FATAL [17:53:28.539] 	System.IO.FileNotFoundException
> > Could not load file or assembly 'RocksDbSharp, Version=9.4.0.50294,  Culture=neutral,  PublicKeyToken=null'. The...ch()
> >    at  System.Thr...eadStart()
> > Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'RocksDbSharp, Version=9.4.0.50294, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> > 
> > File name: 'RocksDbSharp, Version=9.4.0.50294, Culture=neutral, PublicKeyToken=null'
> >    at Neo.Plugins.Storage.Store..ctor(String path)
> >    at Neo.Plugins.Storage.RocksDBStore.GetStore(String path)
> >    at Neo.NeoSystem..ctor(ProtocolSettings settings, IStoreProvider storageProvider, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 137
> >    at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageProvider, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 121
> >    at Neo.CLI.MainService.Start(CommandLineOptions options) in /opt/neoLib/src/Neo.CLI/CLI/MainService.cs:line 381
> >    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
> >    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> >    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> > /opt/start_node.sh: line 2:   667 Aborted                 (core dumped) ( cd /opt/node/Neo.CLI/; dotnet neo-cli.dll )
> > ```
> > 
> > Client has
> > 
> > ```dockerfile
> > RUN apt-get update && apt-get install -y --no-install-recommends \
> > 	    unzip \
> > 	    screen \
> > 	    expect \
> > 	    libsnappy-dev \
> > 	    libleveldb-dev \
> > 	    librocksdb-dev \
> > ```
> 
> Could you show us the `ls` output, where is the RocksDbSharp library located?

Do you know the list of required dlls for this plug-in?

**Comment by shargon** [comment]
> ```cs
> RocksDbSharp
> ```

RocksDbSharp is a nuget, so at least RocksDbSharp.dll

**Comment by vncoelho** [comment]
aheuaea, the .dll is there. However, just the dlls.

For OracleService, for example, we have:
```bash
if [ $PLUGIN_TO_INCLUDE = "OracleService" ]; then
    echo "Going to copy file $ORIGIN_PATH/$PLUGIN_TO_INCLUDE.dll TO $DEST_FOLDER - and some other dependencies"
    cp -ri $ORIGIN_PATH/$PLUGIN_TO_INCLUDE.dll $DEST_FOLDER
    cp -ri $ORIGIN_PATH/Neo.FileStorage.API.dll $DEST_FOLDER
    cp -ri $ORIGIN_PATH/Grpc.Net.Common.dll $DEST_FOLDER
    cp -ri $ORIGIN_PATH/Grpc.Net.ClientFactory.dll $DEST_FOLDER
    cp -ri $ORIGIN_PATH/Grpc.Net.Client.dll $DEST_FOLDER
    cp -ri $ORIGIN_PATH/Grpc.Core.Api.dll $DEST_FOLDER
    cp -ri $ORIGIN_PATH/Grpc.AspNetCore.Server.dll $DEST_FOLDER
    cp -ri $ORIGIN_PATH/Grpc.AspNetCore.Server.ClientFactory.dll $DEST_FOLDER
    cp -ri $ORIGIN_PATH/Google.Protobuf.dll $DEST_FOLDER
    exit 
fi
```

**Comment by cschuchardt88** [comment]
problem solved #3665

**Comment by vncoelho** [comment]
Your suggestion on @cschuchardt88 also solves

```cs
<ItemGroup>
  <ProjectReference Include="..\Plugins\RocksDBStore\RocksDBStore.csproj" />
</ItemGroup>
```

I think that is enough for now.

**Comment by Jim8y** [comment]
close this issue? @vncoelho
