### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#463]
After some experiments disconnecting and connecting nodes, the following error is becoming common:

```cs
[ERROR][11/11/2018 22:00:09][Thread 0004][akka://NeoSystem/user/$b] Network is unreachable
Cause: System.Net.Sockets.SocketException (0x80004005): Network is unreachable
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Neo.Network.UPnP.Discover()
   at Neo.Network.P2P.Peer.OnStart(Int32 port, Int32 ws_port)
   at Neo.Network.P2P.LocalNode.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][11/11/2018 22:00:09][Thread 0003][akka://NeoSystem/user/$b] Error while creating actor instance of type Neo.Network.P2P.LocalNode with 1 args: (Neo.NeoSystem)
Cause: [akka://NeoSystem/user/$b#837781826]: Akka.Actor.PostRestartException: Exception post restart (System.Net.Sockets.SocketException) ---> System.TypeLoadException: Error while creating actor instance of type Neo.Network.P2P.LocalNode with 1 args: (Neo.NeoSystem) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Neo.Network.P2P.LocalNode..ctor(NeoSystem system)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.FinishRecreate(Exception cause, ActorBase failedActor)
   --- End of inner exception stack trace ---
```

**Comment by vncoelho** [comment]
It looks like Akka errors, @erikzhang.
https://stackoverflow.com/questions/45643151/node-in-cluster-stops-listening-for-connections

Maybe the timeout of the TCP protocol and the way the TCP is being terminated is causing some problem, as we are discussing in #462

**Comment by vncoelho** [comment]
This solves with #469 but it is closed because it needs some refinement.

**Comment by jsolman** [comment]
Can this be closed now?

**Comment by vncoelho** [comment]
No men, my internet connection is still bad...hauahaha
