### ISSUE TITLE
Neo v2.9.0,Error occured when I try to convert publickey to address

### ISSUE THREAD

**Issue by shoxive** [neo-project/neo#729]
Hello everyone,I am a newer C# learner.
.NETCore v2.1 adding Neo v2.9.0 with NuGet.
While I am using those code for convert publickey to address
```
var ecpoint = Neo.Cryptography.ECC.ECPoint.FromBytes(getAddressReq.Publickey.HexToBytes(), Neo.Cryptography.ECC.ECCurve.Secp256r1);
var address = Neo.SmartContract.Contract.CreateSignatureContract(ecpoint).Address;
```
Error log as below:
System.TypeInitializationException: The type initializer for 'Neo.Settings' threw an exception. ---> System.IO.FileNotFoundException: The configuration file 'protocol.json' was not found and is not optional. The physical path is '/***/bin/Debug/netcoreapp2.1/protocol.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Neo.Settings..cctor()
   --- End of inner exception stack trace ---
   at Neo.Wallets.Helper.ToAddress(UInt160 scriptHash)
   at CSharpServer/CSharpServer/CSharpServer/Controllers/GenerateAddressController.cs:line 21
   at Neo.SmartContract.Contract.get_Address()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request.

Anyone can give me some advice?

**Comment by shargon** [comment]
You need to copy the `protocol.json` in your directory

**Comment by shoxive** [comment]
@shargon
I dont know where to find the file protocol.json

**Comment by shargon** [comment]
You can use this https://github.com/neo-project/neo-cli/blob/master/neo-cli/protocol.json

**Comment by shoxive** [comment]
Got it,I will try it later.Thanks a lot @sharon

**Comment by shargon** [comment]
If you have any problem, please reopen the issue
